name: starter
description: "A Flutter Stater Kit project to save time of preparing new work."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  animate_do: ^3.3.4
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  get: ^4.6.6
  get_it: ^8.0.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http_parser: ^4.0.0
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  lottie: ^3.1.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  visibility_detector: ^0.4.0+2
  file_picker: ^8.1.4
  path: ^1.9.0
  device_info_plus: ^11.1.1
  package_info_plus: ^8.1.1
  email_validator: ^3.0.0
  dotted_border: ^2.1.0
  flutter_native_splash: ^2.3.13
  fawaterk_payment: ^1.0.1
  #media supporting
  media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.
  easy_paymob: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/splash/
    - assets/images/
    - assets/icons/
    - assets/images/illustration/
    - assets/logo/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
